# Generated by Django 6.1 on 2026-08-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompthistory',
            name='category',
            field=models.CharField(choices=[('coding', 'Coding'), ('study', 'Study'), ('interview', 'Interview'), ('content', 'Content'), ('data', 'Data'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
