# Generated by Django 6.1 on 2026-08-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_prompthistory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompthistory',
            name='is_favorite',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
