# Generated by Django 6.1 on 2026-08-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_prompthistory_is_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('coding', '💻 Coding'), ('study', '📚 Study'), ('interview', '💼 Interview'), ('content', '✍️ Content Writing'), ('data', '📊 Data Analysis'), ('email', '📧 Email Writing'), ('general', '📝 General')], default='general', max_length=20)),
                ('template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
